const router = require('express').Router();
const expenseController = require('../controller/expenseExpressController');
router.get('/readExpense', expenseController.readExpense);
router.get('/readSpecificExpense', expenseController.readSpecificExpense);
router.post('/createExpense', expenseController.createExpense);
router.delete('/deleteExpense', expenseController.deleteExpense); 
router.delete('/deleteIncome', expenseController.deleteIncome);
router.post('/createIncome', expenseController.createIncome); 
router.get('/readIncome', expenseController.readIncome);
module.exports = router;
